# Generated by Django 4.1.7 on 2023-03-05 20:13

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.utils.upload_image_formater),
        ),
    ]
