# Generated by Django 4.1.7 on 2023-03-07 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_menu_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='tag',
        ),
    ]
