# Generated by Django 4.1.7 on 2023-03-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_menu_price_menu_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
