# Generated by Django 4.1.7 on 2023-04-02 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_menu_status_tag_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='name',
        ),
    ]
